### ISSUE TITLE
Error when using Swap

### ISSUE THREAD

**Issue by Andredron** [SoDaRa/Kinetic-Text-Tags#1]
Good afternoon. When using the swap tag in English, everything works fine. But when a non-Latin alphabet is used, the inscription Error and text in the desired language are displayed

`"Все вы потенциальные {swap=мясо@ученики@1.0}{bt}ученики{/bt}{/swap} Академии Небесной Звезды."`
![bandicam_2022-05-29_18-30-30-153](https://user-images.githubusercontent.com/55322207/170877689-cf36068e-2cc9-492d-bf0c-8606b4632575.gif)
Please advise how to fix this

**Comment by SoDaRa** [comment]
Dang, I really missed this for a while huh... Sorry about that. If you still wish for assistance, I can say this is because I added the ERROR text to display if the lengths of the two lines that were being swapped between weren't the same length. So if you have 'bounce', that's 6 characters. So it expects it to swap to something with the same length like "my boy". You can remove that ERROR text if you want if it's otherwise not giving you any issues. But yeah it was just something to help highlight it should be the same length for both.
