### ISSUE TITLE
Animation are restarted after a "wait"

### ISSUE THREAD

**Issue by AndreaBrg** [SoDaRa/Kinetic-Text-Tags#2]
Hi, thanks for the fantastic plugin.
I'm trying to use some of the ATL tags along with a "wait" tag from renpy, but it appears that the ATL animation is restarted after the waiting period has ended.

This is what I'm trying to do:
`"{atl=0.1, bounce_text~10}bounce{w=0.2}{/atl} here we are after the wait."`

Any suggestion?

**Comment by SoDaRa** [comment]
Sorry for getting back to this late. I'm pretty sure this is an issue with how renpy handles text and waits generally. To avoid getting too technical with it, from what I can tell, Renpy more or less kinda treats advancing after a wait tag as it's own line. And recomputes the text to go to the say screen when it advances past it. Which is why the animation resets because it's basically generating new displayables. I'm not sure if there's much of a fix for this sadly. Only way around it would be to have it persist between the update, but the say screen doesn't like doing much trickery in that way. And only other option would be to just show the text yourself separate from the say screen, but that isn't a very viable solution.

That said, I imagine most readers won't be bothered by it. Though if I ever do think of a solution I'll be sure to let you know and post it. But till then I don't think there's much I can do about this issue.
